### ISSUE TITLE
Future features (see TODO comments)

### ISSUE THREAD

**Issue by charlietharas** [charlietharas/hacktrin-scribble#3]
- [ ] support drawing with two hands at once
- [ ] support whole-word detection instead of one letter at a time
- [ ] automatic letter segmentation, use a calibrator to tune
- [ ] correct previously detected letters with spell-check, generally adjust letter detection process by considering the probabilities more carefully with other features in context
